# Generated by Django 2.2.1 on 2019-10-04 08:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('descript', models.TextField()),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'userss',
            },
        ),
        migrations.AddField(
            model_name='loginuser',
            name='name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('content', ckeditor.fields.RichTextField()),
                ('des', ckeditor.fields.RichTextField()),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('click', models.IntegerField(default=0, verbose_name='点击率')),
                ('picture', models.ImageField(upload_to='../static/images/')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.LoginUser', verbose_name='作者')),
                ('tp', models.ManyToManyField(to='article.Type')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
