# Generated by Django 2.2.1 on 2019-10-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191004_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='name',
        ),
    ]
