# Generated by Django 2.2.1 on 2019-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_loginuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='日期'),
        ),
    ]
